### ISSUE TITLE
Problem 1: Convert the web server to use the database

### ISSUE THREAD

**Issue by Djis247** [Djis247/p5#14]
## Problem 1: Convert the web server to use the database

The `webServer.js` we give you in this project is like the Project 5 `webServer.js` in that the app's model fetching routes use the magic `models` rather than a database. Your job is to convert all the routes to use the MongoDB database. There should be no accesses to `models` in your code and your app should work without the line:

```javascript
var models = require('./modelData/photoApp.js').models;
```

in `webServer.js`, Note that any `console.log` statements in `webServer.js` will print to the terminal rather than the browser.

### Web Server API

As in Project 5 the web server will return JSON encoded model data in response to HTTP GET requests to specific URLs. We provide the following specification of what URLs need to be support and what they should return. Your web server should support the following model fetching API:

- `/test` - Return the schema info (`/test/info`) and object counts (`/test/counts`) of the database. This interface is for testing and as an example for you, we provide an implementation that fetches the information from the database. You will not have to change this one.

- `/user/list` - Return the list of users' models appropriate for the navigation sidebar list. Since we anticipate a large numbers of users, this API should only return an array of the user properties needed by the navigation side bar (`_id, first_name, last_name`). It replaces the `models.userListModel()` call in the provided code.

- `/user/:id` - Return the detail information of the user with _id of id. This should return the information we have on the user for the detail view (`_id, first_name, last_name, location, description, occupation`) and replaces the `models.userModel()` call. If something other than the id of a User is provided the response should be an HTTP status of 400 and an informative message.

- `/photosOfUser/:id` - Return the photos of the user with _id of id. This call generates all the model data needed for the photos view including all the photos of the user as well as the comments on the photos. The photos properties should be (`_id, user_id, comments, file_name, date_time`) and the comments array elements should have (`comment, date_time, _id, user`) and only the minimum `user` object information (`_id, first_name, last_name`). This replaces the `models.photoOfUserModel()` call. If something other than the id of a User is provided the response should be an HTTP status of 400 and an informative message. Note this API will need some assembling from multiple different objects in the database. The assignment's `package.json` file fetches the async module to make the assembling the multiple photos easier.

To help you make sure your web server conforms to the proper API we provide a test suite in the sub-directory `test`. **Please make sure that all of the tests in the suite pass before submitting.** See the Testing section below for details.

Your GET requests do not return exactly the same thing that the `models` functions return but they do need to return the information needed by your app so that the model data of each view can be displayed with a single `FetchModel` call. You will need to do subsetting and/or augmentation of the objects coming from the database to build your response to meet the needs of the UI. For this assignment you are not allowed to alter the database schema in anyway.

**\*IMPORTANT!\***    

Implementing these Express request handlers requires interacting with two different "model" data objects. The Mongoose system returns [models](http://mongoosejs.com/docs/models.html) from the objects stored in MongoDB while the request itself should return the data models needed by the Photo App views. Unfortunately since the Mongoose models are set by the database schema and front end models are set by the needs of the UI views they don't align perfectly. Handling these requests will require processing to assemble the model needed by the front end from the Mongoose models returned from the database.

Care needs to be taken when doing this processing since the models returned by Mongoose are JavaScript objects but have special processing done on them so that any modifications that do not match the declared schema are tossed. This means that simply updating a Mongoose model to have the properties expected by the front end doesn't work as expected. One way to work around this is to create a copy of the Mongoose model object. A simple way of doing the copy is to translate the model into JSON and back to an JavaScript objects. The following code fragment does this object cloning:

```javascript
JSON.parse(JSON.stringify(modelObject));
```

by taking `modelObject` converting into a JSON string and then converting it back to a JavaScript object, this time without the methods and special handling done on Mongoose models.

**Comment by Iklimov1** [comment]
As a student, I updated the webServer.js given in this project to use the magic models rather than a database. I converted all the routes to use the MongoDB database.
