### ISSUE TITLE
Code Review: Convert the web server to use the database

### ISSUE THREAD

**Issue by Djis247** [Djis247/p5#16]
#### Problem Statement
The problem is clear: convert the existing web server to use a MongoDB database instead of the previous `models` object. The web server should support a set of API endpoints as specified, returning JSON-encoded data.

#### General Comments
1. Ensure that the entire codebase follows consistent coding style and conventions. This includes variable naming, indentation, and code structure.
2. Properly document your code, especially functions and complex logic. Use meaningful comments and function names.
3. Make sure to test thoroughly, particularly the provided test suite. It's crucial that all tests pass before submitting the code.

#### Specific Feedback
1. **Database Integration:**
   - Replace all usages of the `models` object with MongoDB database queries. The provided code snippet instructs you on how to clone the data for frontend needs. Be careful with data consistency when making this transition.
   
2. **Web Server API Implementation:**
   - Implement the specified API endpoints (`/test`, `/user/list`, `/user/:id`, `/photosOfUser/:id`) as described in the problem statement. Ensure they return the appropriate data in JSON format.
   - For error cases (e.g., invalid user id), return the appropriate HTTP status codes (e.g., 400) and informative error messages.

3. **Data Transformation:**
   - When returning data from the API endpoints, make sure to transform the data as required by the frontend views. This may involve subsetting and augmenting the data objects from the database.

4. **Testing:**
   - Thoroughly test your API endpoints, both in terms of positive and negative scenarios. Verify that the responses match the expected format.
   - Utilize the provided test suite to ensure the correctness of your implementation. All tests should pass before submission.

5. **Error Handling:**
   - Implement proper error handling in case of database connectivity issues or other runtime errors. Consider using try-catch blocks and returning appropriate error responses.

6. **Code Cloning:**
   - As mentioned in the problem statement, when assembling the data for the frontend, create a copy of the Mongoose model object to ensure that any modifications align with the declared schema.

7. **Code Organization:**
   - Organize your code into well-structured modules, ensuring that each module has a clear responsibility.

8. **Dependency Management:**
   - Make sure that all required dependencies, such as the `async` module, are correctly installed and utilized in your project.

9. **Security:**
   - Ensure that your MongoDB queries are protected against potential injection attacks. Use parameterized queries to prevent security vulnerabilities.

10. **Logging:**
    - Consider adding logging to record server activities and errors for debugging and monitoring purposes.

11. **Code Optimization:**
    - Ensure your code is optimized for performance. Avoid unnecessary database queries and data processing.

12. **Database Schema:**
    - Do not alter the database schema unless it is absolutely necessary. Make sure the new structure aligns with the requirements of the web server and frontend.

13. **Resource Cleanup:**
    - Properly close and release resources, such as database connections, when they are no longer needed.

### Conclusion
In summary, the task involves converting an existing web server to use MongoDB for data storage. It's essential to follow the problem statement's instructions carefully, thoroughly test the implementation, and ensure that all API endpoints return the required data in the specified format. Additionally, maintain code quality and follow best practices throughout the development process.

**Comment by dsprad99** [comment]
As a developer, I reviewed the code necessary for functionality of the MongoDB database and approved the code.
