### ISSUE TITLE
Problem 2: New Comments

### ISSUE THREAD

**Issue by Djis247** [Djis247/p5#24]
## Problem 2: New Comments

Once you have implemented user login, the next step is to implement the ability to add comments to photos. In the photo detail view where you display the comments of a photo, add the ability for the currently logged in user to add a comment to the photo. You get to design the user interface (e.g., popup dialog, input field, etc.) for this feature. It should be obvious how to use it and what photo the comment is about. The display of the photo and its comments should be updated immediately to reflect the newly added comment.

For the backend support extend the web server API with the following HTTP POST API:

- `/commentsOfPhoto/:photo_id` - Add a comment to the photo whose id is `photo_id`. The body of the POST requests should be a JSON-encoded body with a single property `comment` that contains the comment's text. The comment object created on the photo must include the identifier of the logged in user and the time when the comment was created. Your implementation should reject any empty comments with a status of 400 (Bad request).

**Comment by Iklimov1** [comment]
As a student I added the comment feature that will save the currently logged in user's comments on the photos. This feature still needs to be combined with the user login portion.
