### ISSUE TITLE
Problem 3: Photo Uploading

### ISSUE THREAD

**Issue by Djis247** [Djis247/p5#25]
## Problem 3: Photo Uploading

Allow users to add new photos. When a user is logged in, the main toolbar should have a button labeled "Add Photo" that allows the current logged in user to upload a photo to the app. We will provide you with an example of how to upload files using HTML in the Hint section below.

Extend the web server to support POST requests to the URL:

- `/photos/new` - Upload a photo for the current user. The body of the POST request should be the file (see hint below). The uploaded files should be placed in the `images` directory under an unique name you generated. The unique name, along with the creation data and logged in user id, should be placed in the new Photo object you create. A response status of 400 should be returned if there is no file in the POST request. See the Hint section for help with this.

**Comment by BareRen** [comment]
As a student, I added the photo upload feature that will upload a picture from the user currently logged in to the user profile they are currently viewing.
