### ISSUE TITLE
Problem 4: Registration and Passwords

### ISSUE THREAD

**Issue by Djis247** [Djis247/p5#26]
## Problem 4: Registration and Passwords

Enhance the `LoginRegister` view component to support new-user registration and passwords. Extend the login portion to add a password field. Add a registration section that allows all the fields of the User object to be filled in. To reduce the chance that the user typos that password the view should contain a an additional copy of the password field and the view should only allow the user to be created if the two password fields are identical. Good security practice requires that the passwords typed by the user shouldn't be visible in the view. Registration should be triggered by a button at the bottom of the page labeled "Register Me". When the button is pushed either an error should be reported explaining **specifically** why it didn't work or a success message should be reported and the register form input fields should be cleared.

For the backend, extend the `User` object schema with a string field `password` that will store the password. This is horribly insecure. See the Extra Credit below if you can't bring yourself to implement something so insecure.

Extend the web server to support POST requests to the URL:
- `/user` - Allows a user to register. The registration POST takes a JSON-encoded body with the following properties: (`login_name, password, first_name, last_name, location, description, occupation`). The post request handler must make sure that the new `login_name` is specified and doesn't already exist. The `first_name`, `last_name`, and `password` must be non-empty strings as well. If the information is valid, then a new user is created in the database. If there is an error, the response should return status 400 and a string indicating the error.

Enhance the `LoginRegister` view to support logging in with a password and check it as part of the post request to `/admin/login`.

**Comment by Cmichau11** [comment]
As a student I added a password option to login as well as created a registration option on the form This feature will be used so anybody can register for a login on the website
