### ISSUE TITLE
Code Review: Problem 1 Simple Login

### ISSUE THREAD

**Issue by Djis247** [Djis247/p5#32]
# Code Review for "Simple Login"

## Overview:
The code changes proposed in this review aim to implement user authentication and authorization in the photo app. This includes adding the ability for users to log in, log out, and displaying appropriate messages and views based on the user's authentication status.

### 1. Implementation of User Authentication:

- The implementation of user authentication using Express sessions and the `/admin/login` and `/admin/logout` routes seems appropriate.

### 2. Frontend Changes:

- The frontend changes to display a personalized message and a "Logout" button when a user is logged in, and showing a "Please Login" message along with the `LoginRegister` view for logged out users are well-defined and seem logically organized.

### 3. Error Handling and Messaging:

- It's good that you've mentioned handling scenarios where the login fails due to incorrect `login_name`. Make sure that appropriate error messages are provided to the user in such cases.

### 4. Handling Unauthorized Requests:

- The requirement to return a status of 401 (Unauthorized) for requests to protected routes when the user is not logged in is important for security. Ensure that all relevant routes (except `/admin/login` and `/admin/logout`) are updated to implement this behavior.

### 5. Database Schema Modification:

- The addition of a `login_name` property to the `User` schema in Mongoose is necessary for user authentication. Verify that this property is being properly utilized in the authentication process.

### 6. Server-side Changes:

- Make sure that the server-side implementation for `/admin/login` and `/admin/logout` handles requests correctly, including appropriate error responses for failed logins and logouts.

### 7. Security Considerations:

- Ensure that sensitive user information, especially passwords, are handled securely. For now, it's mentioned that no passwords are involved, but when implementing password-based authentication in the future, use secure practices like hashing and salting.

### 8. Testing:

- Thoroughly test the authentication flow, including successful logins, failed logins, successful logouts, and unauthorized access to protected routes. Additionally, test edge cases to ensure robustness.

## Conclusion:
The proposed changes for implementing user authentication and authorization in the photo app seem well-defined and logically organized. Ensure that the suggested feedback points are addressed to achieve a secure and functional authentication system. Additionally, comprehensive testing is crucial to verify the correctness and reliability of the implemented features.

**Comment by dsprad99** [comment]
As a programmer I have reviewed the documentation for problem 1 and I approve.
