### ISSUE TITLE
 Code Review for Problem 2: New Comments

### ISSUE THREAD

**Issue by Djis247** [Djis247/p5#34]
## Overall Feedback:

The implementation of the ability to add comments to photos appears to be well-structured and follows the provided requirements. However, there are a few points that should be considered for improvement.

## Frontend Implementation:

1. **User Interface Design**:
   - It's mentioned that the user interface for adding comments should be obvious and intuitive. Ensure that the chosen design (e.g., popup dialog, input field, etc.) is user-friendly and provides clear guidance on how to use it.

2. **Immediate Update of Comments**:
   - It's mentioned that the display of the photo and its comments should be updated immediately to reflect the newly added comment. Verify that this functionality is implemented correctly to provide real-time feedback to users.

## Backend Implementation:

1. **HTTP POST API Endpoint**:
   - The API endpoint `/commentsOfPhoto/:photo_id` should be properly documented in the API documentation for future reference.

2. **Error Handling**:
   - The implementation should correctly handle cases where an empty comment is submitted. Ensure that a status of 400 (Bad request) is returned when an empty comment is detected.

3. **Validation**:
   - Consider adding additional validation checks if required (e.g., maximum comment length, character encoding, etc.).

4. **Security Considerations**:
   - Ensure that the implementation is secure against potential vulnerabilities such as SQL injection, XSS attacks, etc. Properly sanitize and validate user input before processing.

## General Recommendations:

1. **Code Comments and Documentation**:
   - Ensure that the code is well-commented, especially for any complex logic or non-intuitive sections. This will help other developers understand the codebase more easily.

2. **Testing**:
   - Implement unit tests to verify the functionality of the new comments feature, including scenarios like adding a comment, handling empty comments, and ensuring real-time updates.

3. **Error Handling and Logging**:
   - Implement robust error handling and logging mechanisms to capture any unexpected scenarios and facilitate debugging.

4. **Code Review Process**:
   - Consider implementing a formal code review process to catch any potential issues before deploying to production.

5. **Scalability and Performance**:
   - If applicable, consider potential optimizations for scalability and performance, especially if this feature is expected to handle a large number of concurrent users.

Overall, the implementation of the new comments feature seems to be on the right track, but the above points should be considered for further refinement and enhancement. Keep up the good work!

**Comment by Iklimov1** [comment]
As a student, I added the userId to the comment feature payload. I reviewed the code to make sure everything was efficient and working.
